import { prisma } from '../utils/prisma';
import { HttpError } from '../middleware/errors';
import type { AuthUser } from '../types/auth';
import type { Prisma, TaskStatus } from '@prisma/client';
import { publishActivity, publishNotification } from '../websocket/events';
import type { TaskFilters } from '../validators/filters';

const whereFor = (user: AuthUser): Prisma.TaskWhereInput => user.role === 'ADMIN' ? {} : user.role === 'DEVELOPER' ? { assignedDeveloperId: user.id } : { project: { createdById: user.id } };
const assertDeveloper = async (id: number) => { const developer = await prisma.user.findFirst({ where: { id, role: 'DEVELOPER' }, select: { id: true } }); if (!developer) throw new HttpError(422, 'INVALID_ASSIGNEE', 'Tasks must be assigned to a developer'); };
export const list = async (user: AuthUser, filters: TaskFilters) => { const where: Prisma.TaskWhereInput = { ...whereFor(user), status: filters.status, priority: filters.priority, dueDate: filters.from || filters.to ? { gte: filters.from, lte: filters.to ? new Date(new Date(filters.to).setHours(23, 59, 59, 999)) : undefined } : undefined }; const [data, total] = await prisma.$transaction([prisma.task.findMany({ where, include: { project: { select: { id: true, name: true, createdById: true } }, assignedDeveloper: { select: { id: true, name: true } } }, orderBy: [{ priority: 'desc' }, { dueDate: 'asc' }], skip: (filters.page - 1) * filters.limit, take: filters.limit }), prisma.task.count({ where })]); return { data, pagination: { page: filters.page, limit: filters.limit, total, pages: Math.ceil(total / filters.limit) } }; };
export const get = async (id: number, user: AuthUser) => { const task = await prisma.task.findFirst({ where: { id, ...whereFor(user) }, include: { project: true, assignedDeveloper: { select: { id: true, name: true } } } }); if (!task) throw new HttpError(404, 'NOT_FOUND', 'Task not found'); return task; };
export const create = async (user: AuthUser, data: Prisma.TaskUncheckedCreateInput) => { if (user.role === 'DEVELOPER') throw new HttpError(403, 'FORBIDDEN', 'Developers cannot create tasks'); const project = await prisma.project.findFirst({ where: { id: data.projectId, ...(user.role === 'ADMIN' ? {} : { createdById: user.id }) } }); if (!project) throw new HttpError(403, 'FORBIDDEN', 'You do not own this project'); await assertDeveloper(data.assignedDeveloperId); const task = await prisma.$transaction(async (tx) => { const created = await tx.task.create({ data }); await tx.notification.create({ data: { userId: data.assignedDeveloperId, taskId: created.id, type: 'TASK_ASSIGNED', message: `${created.title} was assigned to you` } }); return created; }); const notification = await prisma.notification.findFirst({ where: { taskId: task.id, userId: data.assignedDeveloperId }, orderBy: { createdAt: 'desc' } }); if (notification) publishNotification(notification); return task; };
export const update = async (id: number, user: AuthUser, data: Prisma.TaskUncheckedUpdateInput) => { const task = await get(id, user); if (user.role === 'DEVELOPER' && Object.keys(data).some((key) => key !== 'status')) throw new HttpError(403, 'FORBIDDEN', 'Developers may only update task status'); const assignment = typeof data.assignedDeveloperId === 'number' ? data.assignedDeveloperId : undefined; if (assignment && assignment !== task.assignedDeveloperId) await assertDeveloper(assignment); const updated = await prisma.$transaction(async (tx) => { const next = await tx.task.update({ where: { id: task.id }, data: { ...data, isOverdue: data.status === 'DONE' || data.dueDate ? false : undefined } }); if (assignment && assignment !== task.assignedDeveloperId) await tx.notification.create({ data: { userId: assignment, taskId: task.id, type: 'TASK_ASSIGNED', message: `${task.title} was assigned to you` } }); return next; }); if (assignment && assignment !== task.assignedDeveloperId) { const notification = await prisma.notification.findFirst({ where: { taskId: task.id, userId: assignment }, orderBy: { createdAt: 'desc' } }); if (notification) publishNotification(notification); } return updated; };
export const remove = async (id: number, user: AuthUser) => { const task = await get(id, user); if (user.role === 'DEVELOPER') throw new HttpError(403, 'FORBIDDEN', 'Developers cannot delete tasks'); await prisma.task.delete({ where: { id: task.id } }); };
export const updateStatus = async (id: number, user: AuthUser, status: TaskStatus) => { const task = await get(id, user); if (task.status === status) return task; const result = await prisma.$transaction(async (tx) => { const next = await tx.task.update({ where: { id }, data: { status, isOverdue: false } }); const activity = await tx.activityLog.create({ data: { userId: user.id, projectId: task.projectId, taskId: id, action: `${user.name} moved ${task.title}`, oldStatus: task.status, newStatus: status } }); if (status === 'IN_REVIEW') await tx.notification.create({ data: { userId: task.project.createdById, taskId: id, type: 'TASK_READY_FOR_REVIEW', message: `${task.title} is ready for review` } }); return { next, activity }; }); await publishActivity(result.activity.id); if (status === 'IN_REVIEW') { const notification = await prisma.notification.findFirst({ where: { taskId: id, userId: task.project.createdById }, orderBy: { createdAt: 'desc' } }); if (notification) publishNotification(notification); } return result.next; };
